import React from 'react';
import { ExternalLink, Images, MessageCircle, Play } from 'lucide-react';
import { useInstagram } from '../InstagramContext';
import { formatInstagramDate, getMediaPreview } from '../utils';

export const InstagramMediaGrid: React.FC<{ onOpenComments: () => void }> = ({ onOpenComments }) => {
  const { media, setSelectedMedia } = useInstagram();
  if (!media.length) return <div className="h-72 bg-white border border-slate-200 rounded-xl flex items-center justify-center text-[11px] text-slate-400">Chưa có bài Instagram để hiển thị.</div>;
  return <div className="grid sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-3">{media.map(item => <div key={item.id} className="bg-white border border-slate-200 rounded-xl overflow-hidden group"><div className="relative aspect-[4/3] bg-slate-100 overflow-hidden">{getMediaPreview(item) ? <img src={getMediaPreview(item)} alt="" className="w-full h-full object-cover" /> : null}<div className="absolute top-2 right-2 h-6 px-2 rounded-md bg-black/55 text-white text-[9px] font-bold flex items-center gap-1">{item.media_type === 'VIDEO' ? <Play className="w-3 h-3" /> : item.media_type === 'CAROUSEL_ALBUM' ? <Images className="w-3 h-3" /> : null}{item.media_product_type || item.media_type}</div></div><div className="p-3"><p className="text-[11px] text-slate-700 line-clamp-2 min-h-[32px]">{item.caption || 'Không có caption'}</p><div className="mt-2 flex items-center justify-between text-[9px] text-slate-400"><span>{formatInstagramDate(item.timestamp)}</span><span>♥ {item.like_count || 0} · 💬 {item.comments_count || 0}</span></div><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={() => { setSelectedMedia(item); onOpenComments(); }} className="h-8 rounded-lg bg-slate-900 text-white text-[10px] font-bold inline-flex items-center justify-center gap-1"><MessageCircle className="w-3 h-3" />Bình luận</button><a href={item.permalink || '#'} target="_blank" rel="noreferrer" className="h-8 rounded-lg border border-slate-200 text-slate-600 text-[10px] font-bold inline-flex items-center justify-center gap-1">Instagram <ExternalLink className="w-3 h-3" /></a></div></div></div>)}</div>;
};
